name:  my first workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: welcome
      run: echo "Welcome"
    - name: create file
      run: touch new.txt          
    - name: list files
      run: ls
    - name: read file
      run: cat README.md